"""Cryptography demonstration helpers used by the Streamlit app.

These functions are included for educational demonstration only. In real production
systems, cryptographic design should be reviewed by qualified security specialists.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import os
import secrets
from typing import Dict, Optional


def sha256_digest(message: str) -> str:
    """Return a SHA-256 digest for the supplied message."""
    return hashlib.sha256(message.encode("utf-8")).hexdigest()


def sha3_256_digest(message: str) -> str:
    """Return a SHA3-256 digest for the supplied message."""
    return hashlib.sha3_256(message.encode("utf-8")).hexdigest()


def hmac_sha256(message: str, secret_key: str) -> str:
    """Return an HMAC-SHA256 value for origin integrity demonstration."""
    return hmac.new(secret_key.encode("utf-8"), message.encode("utf-8"), hashlib.sha256).hexdigest()


def generate_demo_key(length_bytes: int = 32) -> str:
    """Generate a URL-safe demonstration key."""
    return secrets.token_urlsafe(length_bytes)


def demonstrate_hash_avalanche(message: str, changed_message: str) -> Dict[str, str]:
    """Compare SHA-256 and SHA3-256 digests for two messages."""
    return {
        "original_message": message,
        "changed_message": changed_message,
        "sha256_original": sha256_digest(message),
        "sha256_changed": sha256_digest(changed_message),
        "sha3_256_original": sha3_256_digest(message),
        "sha3_256_changed": sha3_256_digest(changed_message),
        "interpretation": (
            "A small input change produces a very different digest. This demonstrates why "
            "hash functions are suitable for integrity checks but not for reversible encryption."
        ),
    }


def aes_gcm_encrypt_demo(plaintext: str, password_like_key: str) -> Dict[str, str]:
    """Encrypt a message using AES-GCM if the cryptography package is installed.

    The function derives a 256-bit key from the supplied demonstration key using SHA-256.
    This is intentionally simple for education; production systems should use a dedicated
    key derivation function and managed key storage.
    """
    try:
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM
    except Exception as exc:  # pragma: no cover - depends on local environment
        return {
            "available": "No",
            "error": f"AES-GCM demo requires the cryptography package: {exc}",
        }

    key = hashlib.sha256(password_like_key.encode("utf-8")).digest()
    nonce = os.urandom(12)
    aesgcm = AESGCM(key)
    ciphertext = aesgcm.encrypt(nonce, plaintext.encode("utf-8"), None)

    return {
        "available": "Yes",
        "algorithm": "AES-GCM",
        "nonce_base64": base64.b64encode(nonce).decode("utf-8"),
        "ciphertext_base64": base64.b64encode(ciphertext).decode("utf-8"),
        "note": "AES-GCM provides confidentiality and integrity when used with a unique nonce and protected key.",
    }


def aes_gcm_decrypt_demo(ciphertext_base64: str, nonce_base64: str, password_like_key: str) -> Dict[str, str]:
    """Decrypt AES-GCM output generated by aes_gcm_encrypt_demo."""
    try:
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM
    except Exception as exc:  # pragma: no cover - depends on local environment
        return {
            "available": "No",
            "error": f"AES-GCM demo requires the cryptography package: {exc}",
        }

    try:
        key = hashlib.sha256(password_like_key.encode("utf-8")).digest()
        nonce = base64.b64decode(nonce_base64)
        ciphertext = base64.b64decode(ciphertext_base64)
        plaintext = AESGCM(key).decrypt(nonce, ciphertext, None)
        return {
            "available": "Yes",
            "plaintext": plaintext.decode("utf-8"),
        }
    except Exception as exc:
        return {
            "available": "Yes",
            "error": f"Decryption failed. Check the key, nonce and ciphertext. Details: {exc}",
        }
