"""Data models used by the security assessment engine."""

from dataclasses import dataclass, field, asdict
from datetime import datetime
from typing import Dict, List, Optional


@dataclass
class ScenarioInput:
    """Input supplied by the user or loaded from a sample scenario."""

    title: str
    organisation: str
    scenario_description: str
    asset_category: str
    data_sensitivity: str
    internet_exposure: str
    authentication_strength: str
    patching_status: str
    monitoring_level: str
    third_party_dependency: str
    ai_usage_level: str
    business_criticality: str
    regulatory_context: str = "UK GDPR / Data Protection Act 2018"


@dataclass
class RiskFinding:
    """A single risk finding generated by the engine."""

    asset: str
    threat: str
    vulnerability: str
    cia_goal: str
    likelihood: int
    impact: int
    score: int
    rating: str
    recommended_controls: List[str] = field(default_factory=list)


@dataclass
class AssessmentResult:
    """Full result object produced by the assessment engine."""

    scenario: ScenarioInput
    generated_at: str
    assets: List[str]
    threats: List[str]
    vulnerabilities: List[str]
    cia_impact: Dict[str, str]
    findings: List[RiskFinding]
    firewall_recommendations: List[str]
    ids_recommendations: List[str]
    vulnerability_assessment_recommendations: List[str]
    cryptography_recommendations: List[str]
    legal_ethical_privacy_notes: List[str]
    ai_transparency_notes: List[str]
    executive_summary: str

    def to_dict(self) -> Dict:
        """Return a serialisable dictionary representation of the result."""
        output = asdict(self)
        output["generated_at"] = self.generated_at
        return output


def make_timestamp() -> str:
    """Return a human-readable timestamp for reports."""
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")
